theme: jekyll-theme-minimal
title: Roger Chen ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
description: [<img src="images/Gmail icon.png" width="20">](mailto:rogerchen0418@gmail.com>)
[<img src="images/GitHub icon.png" width="20">](https://github.com/LobbyRokie)
[<img src="images/Linkedin icon.png" width="20">](https://www.linkedin.com/in/rogerchen0418/)
